### PR TITLE
fix: standardizing the TypeScript name in Portuguese documentation

### PR DESCRIPTION
**Pull request by yuriwithowsky**
Standardizing the TypeScript name in Portuguese documentations.

### CODE REVIEW

**Review by danilofuchs — APPROVED** [review]
Thank You!

LGTM

**Comment by khaosdoctor** [comment]
It seems we're having a file misplaced here, I'll take a look

**Review by khaosdoctor — APPROVED** [review]

**Comment by khaosdoctor** [comment]
@yuriwithowsky can you please rebase the master branch onto yours and re-push it so we can run the checks again?

**Comment by yuriwithowsky** [comment]
> @yuriwithowsky can you please rebase the master branch onto yours and re-push it so we can run the checks again?

Done!

**Review by danilofuchs — APPROVED** [review]
LGTM

**Comment by yuriwithowsky** [comment]
broken again 😞

**Comment by orta** [comment]
Hrm, I don't have merge rights anymore - might be worth giving it another try as it seems to be pretty arbitrary https://github.com/OSS-Docs-Tools/code-owner-self-merge/issues/35

**Comment by danilofuchs** [comment]
Ok!
🤞
LGTM

**Pull request merged**
