### PR TITLE
Translate 1 file to ko - Mobile Support

### PR DESCRIPTION
**Pull request by vewevteen**
issue: #6 

en

- [Mobile Support](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground-examples/copy/en/Playground/Tooling/Mobile%20Support.ts)

맞춤법 검사기로 체크하였습니다~ 검토하시다가 수정해야할 사항 있다면 코멘트 부탁드립니다!

### CODE REVIEW

**Review by yeonjuan — APPROVED** [review]
@vewevteen 감사합니다 :)

**Comment by yeonjuan** [comment]
LGTM

**Comment by yeonjuan** [comment]
@orta 
Could you merge these PRs? Merging actions failed. https://github.com/microsoft/TypeScript-Website-Localizations/pull/91, https://github.com/microsoft/TypeScript-Website-Localizations/pull/80

**Comment by orta** [comment]
Thanks, I've added some better logging - so the next time it happens we might know why

**Pull request merged**
