### PR TITLE
[PT-BR] Deep Dive

### PR DESCRIPTION
**Pull request by gustavofabro**
@khaosdoctor 
@danilofuchs

### CODE REVIEW

**Comment by khaosdoctor** [comment]
I haven't forgotten this one, I'll review shortly, had some health issues last month :)

**Review by khaosdoctor — APPROVED** [review]

**Comment by khaosdoctor** [comment]
LGTM

**Comment by khaosdoctor** [comment]
@orta here too, maybe the bot is not getting the right permissions

**Comment by orta** [comment]
The worrying thing is that nothing has changed in the last few days - I've added a bunch of better error logging for the next time it happens.

**Comment by khaosdoctor** [comment]
image

This is what is happening

**Comment by orta** [comment]
Makes sense

**Pull request merged**
