### PR TITLE
[Korean] Fix weird expressions like '_제네릭_' 

### LINKED ISSUE #167: [Korean] Korean document have weird expressions like '_제네릭_'
It looks like that intended expression as Italic, _제네릭_.

In Korean, most of words are composited with postposition(e.g. ~는, ~을). I think it is not correct translation.

In Markdown, in order to express words with italic, we can choose one between `*Italic*` and `_italic_`.

What do you think about using `*itailc*` instead of `_italic_`. Or we can give some whitespace between word and postposition

Please give any feedback to me. 🙏 

<hr>

한글 문서를 보다보면 `_제네릭_`과 같이 적혀있는 문서가 좀 있는 것 같은데, 이게 우리나라 조사(예> ~는, ~을)와 붙으면 마크다운에서 이탤릭 표현으로 인식을 못하고 그냥 하나의 단어로 취급해서 이탤릭체가 적용이 안되는 것 같아보이는데요.

마크다운에서 이탤릭체를 쓸 때, `*이탤릭*`, `_이탤릭_`, 이 2가지를 모두 허용하고 있는데, 이탤릭체 표현하는 곳을 `*이탤릭*`으로 바꾸는 것은 어떨까요? 아니면 단어와 조사 사이에 빈공백 하나 주는 방향도 괜찮을 것 같습니다.

피드백 부탁드립니다! 🙏

### PR DESCRIPTION
**Pull request by Joy1590**
Fix #167

### CODE REVIEW

**Comment by Joy1590** [comment]
@microsoft-github-policy-service agree

**Comment by KunHwanAhn** [comment]
Thank you for PR!! 🙇 

But, the #167 issue is not only `Everyday Types`, but also other pages.

If you use the word `fix #167`, it closes the issue when this PR is merged, even though other pages are not fixed. 🙏

**Comment by Joy1590** [comment]
@KunHwanAhn I used `_[^*\s](?:[^*]*[^*\s])?_` this regex to verify every Italic grammar.

**Comment by dvlprsh** [comment]
LGTM

**Pull request merged**
