### PR TITLE
Add pt-br for getting-started folder

### PR DESCRIPTION
**Pull request by luk3skyw4lker**
Opening PR for translations of files from the get-started folder. first one is already translated (TS for Functional Programmers.md)

### CODE REVIEW

**Review by khaosdoctor — APPROVED** [review]

**Comment by khaosdoctor** [comment]
LGTM

**Comment by khaosdoctor** [comment]
LGTM

**Comment by khaosdoctor** [comment]
So I guess we have a problem, and I can't see the results, @orta can you save us?

**Comment by khaosdoctor** [comment]
LGTM

**Review by danilofuchs — APPROVED** [review]
Great Job! Let me try merging
LGTM

**Comment by luk3skyw4lker** [comment]
@danilofuchs @orta @khaosdoctor 

Is this PR gonna be merged?

**Comment by khaosdoctor** [comment]
We're trying but we can't merge it. Apparently it's not working anymore

**Comment by khaosdoctor** [comment]
LGTM

**Comment by khaosdoctor** [comment]
YAY IT WORKED

**Comment by luk3skyw4lker** [comment]
YEAHHHHHHHH

**Pull request merged**
