### PR TITLE
zh: improve translations

### PR DESCRIPTION
**Pull request by zhongsp**

### CODE REVIEW

**Comment by Kingwl** [comment]
Looks good. @laosb PTAL.

**Comment by orta** [comment]
Should I treat PTAL a version of L G T M?

**Comment by Kingwl** [comment]
Well. Let's move on.

LGTM.

**Comment by Kingwl** [comment]
LGTM.

**Comment by Kingwl** [comment]
Well...Huston, we have a problem.

**Comment by orta** [comment]
Hrm, you're not the first person to hit this today. I wonder what changed.

**Pull request merged**
