### PR TITLE
[ko] Add some Korean translations

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Related issue: #62

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@Bumkeyy @yeonjuan @guyeol 안녕하세요
이 PR 은 
- 이슈 #62 에서 다룬, Localization 관련 메시지들
- https://www.typescriptlang.org/community 페이지

를 한국어로 번역한 PR 입니다.

시간 괜찮으실 때 검토를 한 번 해 주시면 감사하겠습니다.

감사합니다! 😊

**Comment by orta** [comment]
I'd love to get this merged (because the the go-to translated doesn't make much sense when it's in English)

**Comment by bumkeyy** [comment]
LGTM

**Comment by jihoon-seo** [comment]
Despite this PR has been merged, 
in https://www.typescriptlang.org/community page, 
the 'go-to-translated-ver button' is not displayed. 🤔

image

---

Manually accessing https://www.typescriptlang.org/ko/community returns 404 Not Found.

image

---

cf. https://www.typescriptlang.org/docs/handbook/intro.html

image

**Pull request merged**
