### PR TITLE
[PT-BR] By Example.md and Do's and Dont's.md

### PR DESCRIPTION
**Pull request by Perkles**
This PR translates the following documentation to Brazilian Portuguese.
 - Example.md
 - Do's and Dont's.md

### 📝 Notes:
I have translated Do's and Dont's to `Sempre` e `Nunca`. I know that it may look weird, but reads more natural in Portuguese.
Some exemples: 

> _Don't_ ever use the types `Number`, `String`, `Boolean`, `Symbol`, or `Object`

to

> _Nunca_ use os tipos `Number`, `String`, `Boolean`, `Symbol`, ou `Object`

Ref: #1

### CODE REVIEW

**Comment by khaosdoctor** [comment]
I haven't forgotten this one, I'll review it shortly, sorry. I had some health issues

**Review by khaosdoctor — APPROVED** [review]

**Comment by khaosdoctor** [comment]
LGTM

**Comment by khaosdoctor** [comment]
LGTM

**Comment by khaosdoctor** [comment]
@orta I think something is wrong with the bot

**Comment by orta** [comment]
bad bot

**Pull request merged**
