### PR TITLE
Add files from old Korean repo to ko

### PR DESCRIPTION
**Pull request by jihoon-seo**
- This PR adds files from [old Korean repo](https://github.com/typescript-kr/typescript-kr.github.io).
- Plus, I made some enhancements.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
- The failing CI 'local-validate' will be fixed by the PR #56.

**Comment by orta** [comment]
Thanks for fixing the CI!

**Comment by orta** [comment]
I guess I must have missed these files, sorry!

**Comment by orta** [comment]
We should take this as it's porting over existing stuff

**Pull request merged**
