### PR TITLE
Translate Basics Into Chinese

### PR DESCRIPTION
**Pull request by Chorer**

### CODE REVIEW

**Review by awxiaoxian2020 — APPROVED** [review]

**Review by Kingwl — APPROVED** [review]
LGTM

**Comment by Chorer** [comment]
@Kingwl What's wrong with the check ?

**Comment by orta** [comment]
Probably worth trying a second time - I couldn't quite figure out why it would occasionally do this https://github.com/OSS-Docs-Tools/code-owner-self-merge/issues/35

**Comment by Kingwl** [comment]
LGTM

**Comment by Kingwl** [comment]
Cool! It works

**Pull request merged**
