### PR TITLE
Translate 1 file to ko - Typescript Version

### PR DESCRIPTION
**Pull request by vewevteen**
issue: #6 

- [TypeScript Versions](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground-examples/copy/en/Playground/Tooling/TypeScript%20Versions.ts)

맞춤법 검사기로 한번 체크하였습니다~ 혹시 확인하시다가 수정해야할 사항 있다면 코멘트 부탁드립니다!

### CODE REVIEW

**Review by yeonjuan — APPROVED** [review]
번역 감사합니다 :)

**Comment by yeonjuan** [comment]
LGTM

**Comment by yeonjuan** [comment]
LGTM

**Comment by yeonjuan** [comment]
@orta Hi there seems an issue merging. Could you check it or merge this PR?

**Comment by orta** [comment]
Thanks

**Pull request merged**
