### PR TITLE
[PT-BR] translates the file 'dt.ts' to ptbr, from the app section

### PR DESCRIPTION
**Pull request by robertosousa1**
Hello world!
:)
@orta e @PyGera

### CODE REVIEW

**Comment by orta** [comment]
Ace

**Comment by robertosousa1** [comment]
Hi @orta 

previously, I did a similar PR in the previous translation repository and was accepted today

can it impact something?

https://github.com/microsoft/TypeScript-Website/pull/1483

**Comment by orta** [comment]
Perfect, it will get ported over this weekend with the rest!

**Comment by orta** [comment]
Thanks for helping!

**Pull request closed without merging**
